// Converts the source plate into the delivery formats + an inline LQIP.
// Usage: npm run plate
import sharp from 'sharp'
import { writeFileSync } from 'node:fs'

const src = 'public/plate/wood-room-src.jpg'
const meta = await sharp(src).metadata()
console.log('source', meta.width, meta.height)

await sharp(src).webp({ quality: 86 }).toFile('public/plate/wood-room.webp')
await sharp(src).avif({ quality: 58 }).toFile('public/plate/wood-room.avif')
const lqip = await sharp(src).resize(32).blur(1).webp({ quality: 40 }).toBuffer()
writeFileSync('src/stage/lqip.ts', `// generated by scripts/plate.mjs\nexport const PLATE_LQIP = 'data:image/webp;base64,${lqip.toString('base64')}'\n`)
for (const f of ['wood-room.webp', 'wood-room.avif']) {
  const s = (await sharp('public/plate/' + f).metadata())
  console.log(f, s.width + 'x' + s.height, Math.round(s.size / 1024) + ' KB')
}
