// Split the title export (docs/brand/app-title.svg — one path, every letter) into
// letters: subpaths are grouped by containment (a counter belongs to the letter
// whose outline encloses it) and by column (the i's dot joins its stem). Writes
// src/ui/title-glyphs.ts.   node scripts/title-glyphs.mjs
import { readFileSync, writeFileSync } from 'node:fs'

const svg = readFileSync('docs/brand/app-title.svg', 'utf8')
const d = svg.match(/<path[^>]*\sd="([^"]+)"/)[1]
const [, vbW, vbH] = svg.match(/viewBox="0 0 ([\d.]+) ([\d.]+)"/).map(Number)

// tokenise: commands and numbers (with exponents)
const toks = d.match(/[MLHVCZ]|-?(?:\d+\.?\d*|\.\d+)(?:e-?\d+)?/gi)
const subs = []
let cur = null
let x = 0
let y = 0
let i = 0
let cmd = ''
const num = () => Number(toks[i++])
const grow = (px, py) => {
  cur.box[0] = Math.min(cur.box[0], px)
  cur.box[1] = Math.min(cur.box[1], py)
  cur.box[2] = Math.max(cur.box[2], px)
  cur.box[3] = Math.max(cur.box[3], py)
}
while (i < toks.length) {
  if (/^[A-Z]$/i.test(toks[i])) cmd = toks[i++]
  if (cmd === 'M') {
    x = num()
    y = num()
    cur = { d: `M${x} ${y}`, box: [x, y, x, y] }
    subs.push(cur)
    cmd = 'L' // implicit lineto after a moveto's first pair
  } else if (cmd === 'L') {
    x = num()
    y = num()
    cur.d += `L${x} ${y}`
    grow(x, y)
  } else if (cmd === 'H') {
    x = num()
    cur.d += `H${x}`
    grow(x, y)
  } else if (cmd === 'V') {
    y = num()
    cur.d += `V${y}`
    grow(x, y)
  } else if (cmd === 'C') {
    const p = [num(), num(), num(), num(), num(), num()]
    cur.d += `C${p.join(' ')}`
    grow(p[0], p[1])
    grow(p[2], p[3])
    x = p[4]
    y = p[5]
    grow(x, y)
  } else if (cmd === 'Z') {
    cur.d += 'Z'
  } else throw new Error(`unexpected ${cmd}`)
}

const inside = (a, b) => a.box[0] >= b.box[0] - 0.01 && a.box[2] <= b.box[2] + 0.01 && a.box[1] >= b.box[1] - 0.01 && a.box[3] <= b.box[3] + 0.01
const area = (s) => (s.box[2] - s.box[0]) * (s.box[3] - s.box[1])
const outers = subs.filter((s) => !subs.some((o) => o !== s && area(o) > area(s) && inside(s, o)))
const letters = outers.map((o) => ({ parts: [o], box: [...o.box] }))
for (const s of subs) if (!outers.includes(s)) letters.find((l) => inside(s, l.parts[0])).parts.push(s)
// the i: a dot directly above a stem is one letter
for (let a = 0; a < letters.length; a++)
  for (let b = letters.length - 1; b > a; b--) {
    const A = letters[a].box
    const B = letters[b].box
    const ov = Math.min(A[2], B[2]) - Math.max(A[0], B[0])
    if (ov > 0.5 * Math.min(A[2] - A[0], B[2] - B[0])) {
      letters[a].parts.push(...letters[b].parts)
      for (let k = 0; k < 4; k++) letters[a].box[k] = k < 2 ? Math.min(A[k], B[k]) : Math.max(A[k], B[k])
      letters.splice(b, 1)
    }
  }
letters.sort((p, q) => p.box[0] - q.box[0])
const text = 'MeetZENDesignTeam'
if (letters.length !== text.length) throw new Error(`found ${letters.length} letters, expected ${text.length}`)
// 0.01 units is far below a pixel at any size the card is shown (≈ 1.1 px per unit at most)
const tidy = (d) => d.replace(/-?\d+\.?\d*(?:e-?\d+)?/g, (n) => String(+(+n).toFixed(2)))
const out = letters.map((l, k) => ({ ch: text[k], d: tidy(l.parts.map((p) => p.d).join('')), box: l.box.map((v) => +v.toFixed(2)) }))
writeFileSync(
  'src/ui/title-glyphs.ts',
  `// GENERATED by scripts/title-glyphs.mjs from docs/brand/app-title.svg — do not edit by hand.
// "Meet ZEN Design Team" as Artur set it in Figma (Nunito), one outline per letter, in
// the export's own units (${vbW} × ${vbH}; the g's descender reaches y ≈ 54).
export type Glyph = { ch: string; d: string; box: [number, number, number, number] }
export const TITLE_BOX = { w: ${vbW}, h: ${vbH} }
export const GLYPHS: Glyph[] = ${JSON.stringify(out, null, 2)}
`,
)
console.log(out.map((g) => `${g.ch} ${g.box.join(',')}`).join('\n'))
